python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.1/poisson1 --bsm_sde.vol=0.1 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.2/poisson1 --bsm_sde.vol=0.2 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.3/poisson1 --bsm_sde.vol=0.3 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.4/poisson1 --bsm_sde.vol=0.4 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.5/poisson1 --bsm_sde.vol=0.5 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.6/poisson1 --bsm_sde.vol=0.6 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.7/poisson1 --bsm_sde.vol=0.7 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.8/poisson1 --bsm_sde.vol=0.8 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/d3pg/vol0.9/poisson1 --bsm_sde.vol=0.9 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0

python run_d3pg.py @run_configs/agents/d3pg.cfg --env_config=run_configs/envs/dr_bsm_vanilla.yaml --logger_prefix=logs/dr_bsm_vanilla/d3pg/dr_vol/poisson1 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0

python run_benchmark.py @run_configs/agents/delta.cfg --env_config=run_configs/envs/bsm_vanilla.yaml --logger_prefix=logs/bsm_vanilla/delta/vol0.2/poisson1 --bsm_sde.vol=0.2 --bsm_portfolio.client_trade_poisson_rate=1.0 --sabr_portfolio.client_trade_poisson_rate=1.0
